import UIKit

final class CommunityProfileDetailViewController: LMViewController {
    private let member: CommunityProfile; private let follow = UIButton(type: .system)
    // Keep the portrait and scenery true to the source image; the fade only
    // begins near the identity copy at the bottom of the hero.
    private let heroShade = LMGradientView(colors: [.clear, .clear, UIColor.black.withAlphaComponent(0.70)], horizontal: false)
    init(member: CommunityProfile) { self.member = member; super.init(nibName: nil, bundle: nil) }
    required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() {
        super.viewDidLoad(); title = ""; navigationItem.rightBarButtonItem = UIBarButtonItem(image: UIImage(systemName: "ellipsis"), style: .plain, target: self, action: #selector(safety))
        let scroll = UIScrollView(); scroll.showsVerticalScrollIndicator = false; view.addSubview(scroll); scroll.pin(to: view)
        let content = UIView(); content.translatesAutoresizingMaskIntoConstraints = false; scroll.addSubview(content); NSLayoutConstraint.activate([content.topAnchor.constraint(equalTo: scroll.topAnchor), content.leadingAnchor.constraint(equalTo: scroll.leadingAnchor), content.trailingAnchor.constraint(equalTo: scroll.trailingAnchor), content.bottomAnchor.constraint(equalTo: scroll.bottomAnchor), content.widthAnchor.constraint(equalTo: scroll.widthAnchor)])
        let hero = UIImageView(image: UIImage(named: member.image)); hero.contentMode = .scaleAspectFill; hero.clipsToBounds = true; hero.translatesAutoresizingMaskIntoConstraints = false; content.addSubview(hero)
        heroShade.translatesAutoresizingMaskIntoConstraints = false; hero.addSubview(heroShade)
        let live = UILabel.lm(member.isLive ? "  ● LIVE  " : "  RECENTLY ACTIVE  ", size: 10, weight: .heavy, color: .white); live.backgroundColor = member.isLive ? LMTheme.pink : UIColor.black.withAlphaComponent(0.45); live.round(10)
        let name = UILabel.lm("\(member.name), \(member.age)", size: 29, weight: .heavy); let country = UILabel.lm("\(member.country)   \(member.region)", size: 13, weight: .semibold, color: .white.withAlphaComponent(0.78)); [live,name,country].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; content.addSubview($0) }
        let bioTitle = UILabel.lm("ABOUT", size: 10, weight: .heavy, color: LMTheme.muted); let bio = UILabel.lm(member.profileNote, size: 15, weight: .medium, color: .white.withAlphaComponent(0.86)); bio.numberOfLines = 0
        let interestTitle = UILabel.lm("INTEREST SIGNALS", size: 10, weight: .heavy, color: LMTheme.muted); let interests = UIStackView(); interests.axis = .horizontal; interests.spacing = 8; member.interestSignals.forEach { value in let chip = UILabel.lm("  \(value)  ", size: 11, weight: .bold); chip.backgroundColor = LMTheme.panel2; chip.round(13); chip.textAlignment = .center; chip.heightAnchor.constraint(equalToConstant: 27).isActive = true; interests.addArrangedSubview(chip) }
        let social = UIView(); social.backgroundColor = LMTheme.panel; social.round(11); let statStack = UIStackView(); statStack.axis = .horizontal; statStack.distribution = .fillEqually; statStack.translatesAutoresizingMaskIntoConstraints = false; social.addSubview(statStack); [("\(120 + member.declaredAge)", "Followers"), ("\(34 + member.declaredAge)", "Following"), (member.presenceTier, "Presence")].forEach { value,label in let box = UIView(); let v = UILabel.lm(value, size: 17, weight: .bold); let l = UILabel.lm(label, size: 10, color: LMTheme.muted); v.textAlignment = .center; l.textAlignment = .center; [v,l].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; box.addSubview($0) }; NSLayoutConstraint.activate([v.topAnchor.constraint(equalTo: box.topAnchor, constant: 13), v.centerXAnchor.constraint(equalTo: box.centerXAnchor), l.topAnchor.constraint(equalTo: v.bottomAnchor, constant: 4), l.centerXAnchor.constraint(equalTo: box.centerXAnchor)]); statStack.addArrangedSubview(box) }
        let buttons = UIStackView(); buttons.axis = .horizontal; buttons.spacing = 9; buttons.distribution = .fill; follow.setTitle("Follow".lmLocalized, for: .normal); follow.setTitleColor(.white, for: .normal); follow.titleLabel?.font = LMTheme.font(size: 15, weight: .bold); follow.backgroundColor = LMTheme.pink; follow.round(24); follow.widthAnchor.constraint(equalToConstant: 105).isActive = true; follow.addTarget(self, action: #selector(toggleFollow), for: .touchUpInside)
        let message = actionButton("Message", "bubble.left.fill"); message.addAction(UIAction { [weak self] _ in guard let self else { return }; self.navigationController?.pushViewController(MutualConversationViewController(member: self.member), animated: true) }, for: .touchUpInside)
        let call = actionButton("", "video.fill"); call.widthAnchor.constraint(equalToConstant: 52).isActive = true; call.addAction(UIAction { [weak self] _ in guard let self else { return }; guard LookMeExperienceStore.shared.isMutual(with: self.member.id) else { self.present(LMNoticeViewController(style: .warning, title: "Mutual follow required", message: "You and \(self.member.name) must both choose to follow each other before calling."), animated: true); return }; CallPermissionManager.request(video: true, from: self) { self.present(VideoCallViewController(member: self.member, mode: .video), animated: true) } }, for: .touchUpInside)
        buttons.addArrangedSubview(follow); buttons.addArrangedSubview(message); buttons.addArrangedSubview(call)
        [bioTitle,bio,interestTitle,interests,social,buttons].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; content.addSubview($0) }
        NSLayoutConstraint.activate([hero.topAnchor.constraint(equalTo: content.topAnchor), hero.leadingAnchor.constraint(equalTo: content.leadingAnchor), hero.trailingAnchor.constraint(equalTo: content.trailingAnchor), hero.heightAnchor.constraint(equalToConstant: 505), heroShade.topAnchor.constraint(equalTo: hero.topAnchor), heroShade.leadingAnchor.constraint(equalTo: hero.leadingAnchor), heroShade.trailingAnchor.constraint(equalTo: hero.trailingAnchor), heroShade.bottomAnchor.constraint(equalTo: hero.bottomAnchor), live.leadingAnchor.constraint(equalTo: content.leadingAnchor, constant: 18), live.bottomAnchor.constraint(equalTo: name.topAnchor, constant: -12), live.heightAnchor.constraint(equalToConstant: 21), name.leadingAnchor.constraint(equalTo: live.leadingAnchor), name.bottomAnchor.constraint(equalTo: country.topAnchor, constant: -5), country.leadingAnchor.constraint(equalTo: name.leadingAnchor), country.bottomAnchor.constraint(equalTo: hero.bottomAnchor, constant: -20), bioTitle.topAnchor.constraint(equalTo: hero.bottomAnchor, constant: 20), bioTitle.leadingAnchor.constraint(equalTo: content.leadingAnchor, constant: 18), bio.topAnchor.constraint(equalTo: bioTitle.bottomAnchor, constant: 8), bio.leadingAnchor.constraint(equalTo: bioTitle.leadingAnchor), bio.trailingAnchor.constraint(equalTo: content.trailingAnchor, constant: -18), interestTitle.topAnchor.constraint(equalTo: bio.bottomAnchor, constant: 22), interestTitle.leadingAnchor.constraint(equalTo: bio.leadingAnchor), interests.topAnchor.constraint(equalTo: interestTitle.bottomAnchor, constant: 9), interests.leadingAnchor.constraint(equalTo: bio.leadingAnchor), social.topAnchor.constraint(equalTo: interests.bottomAnchor, constant: 20), social.leadingAnchor.constraint(equalTo: bio.leadingAnchor), social.trailingAnchor.constraint(equalTo: bio.trailingAnchor), social.heightAnchor.constraint(equalToConstant: 66), statStack.topAnchor.constraint(equalTo: social.topAnchor), statStack.leadingAnchor.constraint(equalTo: social.leadingAnchor), statStack.trailingAnchor.constraint(equalTo: social.trailingAnchor), statStack.bottomAnchor.constraint(equalTo: social.bottomAnchor), buttons.topAnchor.constraint(equalTo: social.bottomAnchor, constant: 18), buttons.leadingAnchor.constraint(equalTo: bio.leadingAnchor), buttons.trailingAnchor.constraint(equalTo: bio.trailingAnchor), buttons.heightAnchor.constraint(equalToConstant: 50), buttons.bottomAnchor.constraint(equalTo: content.bottomAnchor, constant: -24)])
        updateFollow(); NotificationCenter.default.addObserver(forName: .lookMeStoreChanged, object: nil, queue: .main) { [weak self] _ in guard let self, LookMeExperienceStore.shared.blockedUsers.contains(self.member.id) else { return }; self.navigationController?.popViewController(animated: true) }
    }
    private func actionButton(_ title: String, _ symbol: String) -> UIButton { let b = UIButton.lm(title, symbol: symbol); b.backgroundColor = LMTheme.panel2; b.round(24); return b }
    @objc private func toggleFollow() { LookMeExperienceStore.shared.toggleFollow(member.id); updateFollow() }
    @objc private func safety() { SafetyCoordinator.present(from: self, target: .init(id: "profile:\(member.id)", type: "profile", userID: member.id, displayName: member.name)) }
    private func updateFollow() { let on = LookMeExperienceStore.shared.following.contains(member.id); follow.setTitle((on ? "Following" : "Follow").lmLocalized, for: .normal); follow.backgroundColor = on ? LMTheme.violet : LMTheme.pink }
}

enum CallMode { case voice, video }

final class VideoCallViewController: UIViewController {
    private let member: CommunityProfile; private let time = UILabel.lm("00:00", size: 14, weight: .semibold); private var timer: Timer?; private var seconds = 0
    private let mode: CallMode
    init(member: CommunityProfile, mode: CallMode = .video) { self.member = member; self.mode = mode; super.init(nibName: nil, bundle: nil); modalPresentationStyle = .fullScreen }
    required init?(coder: NSCoder) { fatalError() }
    override var preferredStatusBarStyle: UIStatusBarStyle { .lightContent }
    override func viewDidLoad() {
        super.viewDidLoad(); let image = UIImageView(image: UIImage(named: member.image)); image.contentMode = .scaleAspectFill; view.addSubview(image); image.pin(to: view)
        let blur = UIVisualEffectView(effect: UIBlurEffect(style: .systemUltraThinMaterialDark)); blur.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(blur); NSLayoutConstraint.activate([blur.leadingAnchor.constraint(equalTo: view.leadingAnchor), blur.trailingAnchor.constraint(equalTo: view.trailingAnchor), blur.bottomAnchor.constraint(equalTo: view.bottomAnchor), blur.heightAnchor.constraint(equalToConstant: 250)])
        if mode == .voice { let cover = UIVisualEffectView(effect: UIBlurEffect(style: .systemMaterialDark)); image.addSubview(cover); cover.pin(to: image) }
        let name = UILabel.lm(member.name, size: 27, weight: .bold); let note = UILabel.lm(mode == .video ? "Direct video call" : "Direct voice call", size: 13, weight: .medium, color: .white.withAlphaComponent(0.78)); [name,note,time].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; view.addSubview($0) }
        let controls = UIStackView(); controls.axis = .horizontal; controls.distribution = .fillEqually; controls.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(controls)
        let callControls = mode == .video ? [("mic.fill", "Mic"), ("video.fill", "Camera"), ("speaker.wave.2.fill", "Speaker")] : [("mic.fill", "Mic"), ("speaker.wave.2.fill", "Speaker")]
        callControls.forEach { symbol,title in let control = CallControl(symbol: symbol, title: title); controls.addArrangedSubview(control) }
        let end = UIButton(type: .system); end.setImage(UIImage(systemName: "phone.down.fill", withConfiguration: UIImage.SymbolConfiguration(pointSize: 25, weight: .bold)), for: .normal); end.tintColor = .white; end.backgroundColor = .systemRed; end.round(34); end.addTarget(self, action: #selector(close), for: .touchUpInside); end.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(end)
        NSLayoutConstraint.activate([name.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 26), name.centerXAnchor.constraint(equalTo: view.centerXAnchor), note.topAnchor.constraint(equalTo: name.bottomAnchor, constant: 4), note.centerXAnchor.constraint(equalTo: view.centerXAnchor), time.topAnchor.constraint(equalTo: note.bottomAnchor, constant: 7), time.centerXAnchor.constraint(equalTo: view.centerXAnchor), controls.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 25), controls.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -25), controls.bottomAnchor.constraint(equalTo: end.topAnchor, constant: -22), controls.heightAnchor.constraint(equalToConstant: 86), end.centerXAnchor.constraint(equalTo: view.centerXAnchor), end.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -22), end.widthAnchor.constraint(equalToConstant: 68), end.heightAnchor.constraint(equalTo: end.widthAnchor)])
        timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in guard let self else { return }; seconds += 1; time.text = String(format: "%02d:%02d", seconds / 60, seconds % 60) }
    }
    @objc private func close() { timer?.invalidate(); dismiss(animated: true) }
}

final class CallControl: UIButton {
    init(symbol: String, title: String) { super.init(frame: .zero); let circle = UIView(); circle.isUserInteractionEnabled = false; circle.backgroundColor = UIColor.white.withAlphaComponent(0.17); circle.round(27); circle.translatesAutoresizingMaskIntoConstraints = false; addSubview(circle); let image = UIImageView(image: UIImage(systemName: symbol)); image.tintColor = .white; image.translatesAutoresizingMaskIntoConstraints = false; circle.addSubview(image); let label = UILabel.lm(title, size: 11, weight: .semibold); label.translatesAutoresizingMaskIntoConstraints = false; addSubview(label); NSLayoutConstraint.activate([circle.topAnchor.constraint(equalTo: topAnchor), circle.centerXAnchor.constraint(equalTo: centerXAnchor), circle.widthAnchor.constraint(equalToConstant: 54), circle.heightAnchor.constraint(equalTo: circle.widthAnchor), image.centerXAnchor.constraint(equalTo: circle.centerXAnchor), image.centerYAnchor.constraint(equalTo: circle.centerYAnchor), label.topAnchor.constraint(equalTo: circle.bottomAnchor, constant: 7), label.centerXAnchor.constraint(equalTo: centerXAnchor)]); addAction(UIAction { [weak self] _ in self?.isSelected.toggle(); self?.alpha = self?.isSelected == true ? 0.48 : 1 }, for: .touchUpInside) }
    required init?(coder: NSCoder) { fatalError() }
}
