import UIKit

final class ContentCommentsViewController: LMViewController, UITableViewDataSource, UITableViewDelegate {
    private let contentID: String; private let heading: String; private let table = UITableView(); private let field = UITextField(); private let empty = UILabel.lm("Start a respectful conversation.", size: 13, weight: .medium, color: LMTheme.muted)
    private let replyCount = UILabel.lm(size: 11, weight: .semibold, color: LMTheme.pinkSoft)
    private var comments: [CommunityReplyRecord] { LookMeExperienceStore.shared.comments(for: contentID) }
    init(contentID: String, title: String) { self.contentID = contentID; heading = title; super.init(nibName: nil, bundle: nil); modalPresentationStyle = .pageSheet; if let sheet = sheetPresentationController { sheet.detents = [.medium(), .large()]; sheet.prefersGrabberVisible = true; sheet.preferredCornerRadius = 28 } }
    required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() {
        super.viewDidLoad()
        let title = UILabel.lm(heading, size: 19, weight: .bold); title.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(title)
        replyCount.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(replyCount)
        table.backgroundColor = .clear; table.separatorStyle = .none; table.dataSource = self; table.delegate = self; table.register(CommentRowCell.self, forCellReuseIdentifier: "comment"); table.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(table)
        empty.textAlignment = .center; empty.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(empty)
        let composer = UIView(); composer.backgroundColor = LMTheme.panel; composer.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(composer)
        field.accessibilityIdentifier = "comments.input"; field.attributedPlaceholder = NSAttributedString(string: "Add a comment", attributes: [.foregroundColor: LMTheme.muted]); field.textColor = .white; field.font = LMTheme.font(size: 14, weight: .medium); field.backgroundColor = LMTheme.panel2; field.round(20); field.setLeftPadding(14); field.returnKeyType = .send; field.addTarget(self, action: #selector(send), for: .editingDidEndOnExit); field.translatesAutoresizingMaskIntoConstraints = false; composer.addSubview(field)
        let sendButton = UIButton(type: .system); sendButton.accessibilityIdentifier = "comments.send"; sendButton.accessibilityLabel = "Post comment"; sendButton.setImage(UIImage(systemName: "arrow.up", withConfiguration: UIImage.SymbolConfiguration(pointSize: 17, weight: .bold)), for: .normal); sendButton.tintColor = .white; sendButton.backgroundColor = LMTheme.pink; sendButton.round(19); sendButton.addTarget(self, action: #selector(send), for: .touchUpInside); sendButton.translatesAutoresizingMaskIntoConstraints = false; composer.addSubview(sendButton)
        NSLayoutConstraint.activate([title.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 6), title.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 18), replyCount.leadingAnchor.constraint(equalTo: title.leadingAnchor), replyCount.topAnchor.constraint(equalTo: title.bottomAnchor, constant: 2), table.topAnchor.constraint(equalTo: replyCount.bottomAnchor, constant: 8), table.leadingAnchor.constraint(equalTo: view.leadingAnchor), table.trailingAnchor.constraint(equalTo: view.trailingAnchor), table.bottomAnchor.constraint(equalTo: composer.topAnchor), empty.centerXAnchor.constraint(equalTo: table.centerXAnchor), empty.centerYAnchor.constraint(equalTo: table.centerYAnchor), composer.leadingAnchor.constraint(equalTo: view.leadingAnchor), composer.trailingAnchor.constraint(equalTo: view.trailingAnchor), composer.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor), composer.heightAnchor.constraint(equalToConstant: 66), field.leadingAnchor.constraint(equalTo: composer.leadingAnchor, constant: 12), field.centerYAnchor.constraint(equalTo: composer.centerYAnchor), field.heightAnchor.constraint(equalToConstant: 41), sendButton.leadingAnchor.constraint(equalTo: field.trailingAnchor, constant: 8), sendButton.trailingAnchor.constraint(equalTo: composer.trailingAnchor, constant: -12), sendButton.centerYAnchor.constraint(equalTo: composer.centerYAnchor), sendButton.widthAnchor.constraint(equalToConstant: 38), sendButton.heightAnchor.constraint(equalTo: sendButton.widthAnchor)])
        NotificationCenter.default.addObserver(forName: .lookMeStoreChanged, object: nil, queue: .main) { [weak self] _ in self?.refresh() }; refresh()
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int { comments.count }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell { let comment = comments[indexPath.row]; let cell = tableView.dequeueReusableCell(withIdentifier: "comment", for: indexPath) as! CommentRowCell; cell.configure(comment); cell.onMore = { [weak self] in guard let self else { return }; SafetyCoordinator.present(from: self, target: .init(id: "comment:\(comment.id.uuidString)", type: "comment", userID: comment.authorID == "me" ? nil : comment.authorID, displayName: comment.authorName)) }; return cell }
    @objc private func send() { guard let text = field.text?.trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty else { return }; guard LookMeContentPolicy.allows(text) else { present(LMNoticeViewController(style: .warning, title: "Comment not posted", message: "Please revise content that may be unsafe, explicit, threatening or spam-like."), animated: true); return }; LookMeExperienceStore.shared.addComment(text, to: contentID); field.text = ""; field.resignFirstResponder(); DispatchQueue.main.async { [weak self] in guard let self, !self.comments.isEmpty else { return }; self.table.scrollToRow(at: IndexPath(row: self.comments.count - 1, section: 0), at: .bottom, animated: true) } }
    private func refresh() { table.reloadData(); empty.isHidden = !comments.isEmpty; replyCount.text = "Community replies · \(comments.count)" }
}

final class CommentRowCell: UITableViewCell {
    var onMore: (() -> Void)?; private let avatar = UIImageView(); private let initial = UILabel.lm(size: 13, weight: .bold); private let name = UILabel.lm(size: 13, weight: .bold); private let body = UILabel.lm(size: 14, weight: .medium); private let time = UILabel.lm(size: 10, color: LMTheme.muted); private let more = UIButton(type: .system)
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) { super.init(style: style, reuseIdentifier: reuseIdentifier); backgroundColor = .clear; selectionStyle = .none; avatar.backgroundColor = LMTheme.violet; avatar.contentMode = .scaleAspectFill; avatar.clipsToBounds = true; avatar.round(19); initial.textAlignment = .center; body.numberOfLines = 0; more.setImage(UIImage(systemName: "ellipsis"), for: .normal); more.tintColor = LMTheme.muted; more.addTarget(self, action: #selector(moreTap), for: .touchUpInside); [avatar,name,body,time,more].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview($0) }; initial.translatesAutoresizingMaskIntoConstraints = false; avatar.addSubview(initial); NSLayoutConstraint.activate([avatar.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 16), avatar.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 13), avatar.widthAnchor.constraint(equalToConstant: 38), avatar.heightAnchor.constraint(equalTo: avatar.widthAnchor), initial.centerXAnchor.constraint(equalTo: avatar.centerXAnchor), initial.centerYAnchor.constraint(equalTo: avatar.centerYAnchor), name.leadingAnchor.constraint(equalTo: avatar.trailingAnchor, constant: 11), name.topAnchor.constraint(equalTo: avatar.topAnchor), more.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -13), more.centerYAnchor.constraint(equalTo: name.centerYAnchor), more.widthAnchor.constraint(equalToConstant: 36), more.heightAnchor.constraint(equalToConstant: 36), body.leadingAnchor.constraint(equalTo: name.leadingAnchor), body.topAnchor.constraint(equalTo: name.bottomAnchor, constant: 4), body.trailingAnchor.constraint(equalTo: more.leadingAnchor, constant: -4), time.leadingAnchor.constraint(equalTo: body.leadingAnchor), time.topAnchor.constraint(equalTo: body.bottomAnchor, constant: 6), time.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -12)]) }
    required init?(coder: NSCoder) { fatalError() }
    override func prepareForReuse() { super.prepareForReuse(); onMore = nil; avatar.image = nil; initial.isHidden = false }
    func configure(_ comment: CommunityReplyRecord) { let portraitName: String? = comment.authorID == "me" ? CommunityMediaRegistry.currentUserAvatarAsset : LookMeCommunityDirectory.members.first(where: { $0.id == comment.authorID })?.image; avatar.image = portraitName.flatMap(UIImage.init(named:)); initial.isHidden = avatar.image != nil; initial.text = String(comment.authorName.prefix(1)).uppercased(); avatar.isAccessibilityElement = true; avatar.accessibilityIdentifier = "comment.avatar.\(comment.authorID)"; avatar.accessibilityLabel = "\(comment.authorName)'s avatar"; avatar.accessibilityValue = portraitName; name.text = comment.authorName; body.text = comment.text; time.text = LookMeLanguageCenter.shared.relativeTime(from: comment.createdAt); more.accessibilityIdentifier = "comment.safety.\(comment.id.uuidString)"; more.accessibilityLabel = "Report or block \(comment.authorName)" }
    @objc private func moreTap() { onMore?() }
}
