import UIKit

struct EffectCatalogItem { let id: String; let name: String; let symbol: String; let price: Int; let category: String; let accent: UIColor }

final class EffectBoutiqueViewController: LMViewController, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    private let allItems = [
        EffectCatalogItem(id: "rose", name: "Rose Signal", symbol: "🌹", price: 25, category: "Live Gift", accent: UIColor(red: 0.85, green: 0.18, blue: 0.55, alpha: 1)),
        EffectCatalogItem(id: "roadster", name: "Roadster Entry", symbol: "🏎️", price: 680, category: "Entrance FX", accent: UIColor(red: 0.90, green: 0.58, blue: 0.12, alpha: 1)),
        EffectCatalogItem(id: "comet", name: "Comet Entry", symbol: "☄️", price: 260, category: "Entrance FX", accent: UIColor(red: 0.12, green: 0.75, blue: 0.62, alpha: 1)),
        EffectCatalogItem(id: "kiss", name: "Sweet Kiss", symbol: "💋", price: 60, category: "Live Gift", accent: UIColor(red: 1, green: 0.15, blue: 0.45, alpha: 1)),
        EffectCatalogItem(id: "crown", name: "Royal Crown", symbol: "👑", price: 180, category: "Live Gift", accent: UIColor(red: 0.86, green: 0.56, blue: 0.10, alpha: 1)),
        EffectCatalogItem(id: "rocket", name: "Night Rocket", symbol: "🚀", price: 520, category: "Live Gift", accent: UIColor(red: 0.48, green: 0.28, blue: 0.95, alpha: 1)),
        EffectCatalogItem(id: "aurora", name: "Aurora Aura", symbol: "🔮", price: 340, category: "Profile Aura", accent: UIColor(red: 0.58, green: 0.20, blue: 0.96, alpha: 1)),
        EffectCatalogItem(id: "heart", name: "Heart Aura", symbol: "💗", price: 220, category: "Profile Aura", accent: UIColor(red: 1, green: 0.27, blue: 0.61, alpha: 1)),
        EffectCatalogItem(id: "star", name: "Starlight Aura", symbol: "🌟", price: 460, category: "Profile Aura", accent: UIColor(red: 0.98, green: 0.66, blue: 0.12, alpha: 1))
    ]
    private var category = "All"; private var collectionView: UICollectionView!; private let balance = UILabel.lm(size: 14, weight: .bold)
    private var items: [EffectCatalogItem] { category == "All" ? allItems : allItems.filter { $0.category == category } }
    override func viewDidLoad() {
        super.viewDidLoad(); title = "Store"
        let layout = UICollectionViewFlowLayout(); layout.minimumLineSpacing = 10; layout.minimumInteritemSpacing = 9; layout.sectionInset = UIEdgeInsets(top: 4, left: 12, bottom: 105, right: 12); layout.headerReferenceSize = CGSize(width: view.bounds.width, height: 245)
        collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout); collectionView.backgroundColor = .clear; collectionView.showsVerticalScrollIndicator = false; collectionView.dataSource = self; collectionView.delegate = self
        collectionView.register(EffectCatalogCell.self, forCellWithReuseIdentifier: "storeItem"); collectionView.register(EffectCatalogHeader.self, forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "storeHeader"); view.addSubview(collectionView); collectionView.pin(to: view)
        buildBottomBar(); refreshBalance(); NotificationCenter.default.addObserver(forName: .lookMeStoreChanged, object: nil, queue: .main) { [weak self] _ in self?.refreshBalance(); self?.collectionView.reloadData() }
    }
    private func buildBottomBar() { let bar = UIView(); bar.backgroundColor = UIColor(red: 0.035, green: 0.008, blue: 0.13, alpha: 0.98); bar.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(bar); let balancePill = UIView(); balancePill.backgroundColor = LMTheme.panel2; balancePill.round(20); balancePill.translatesAutoresizingMaskIntoConstraints = false; bar.addSubview(balancePill); let coin = UIImageView(image: UIImage(systemName: "seal.fill")); coin.tintColor = UIColor(red: 1, green: 0.78, blue: 0.22, alpha: 1); [coin,balance].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; balancePill.addSubview($0) }; let recharge = UIButton.lm("Get coins", symbol: "plus.circle.fill"); recharge.titleLabel?.lineBreakMode = .byClipping; recharge.backgroundColor = LMTheme.pink; recharge.round(21); recharge.translatesAutoresizingMaskIntoConstraints = false; recharge.addTarget(self, action: #selector(rechargeTapped), for: .touchUpInside); bar.addSubview(recharge); NSLayoutConstraint.activate([bar.leadingAnchor.constraint(equalTo: view.leadingAnchor), bar.trailingAnchor.constraint(equalTo: view.trailingAnchor), bar.bottomAnchor.constraint(equalTo: view.bottomAnchor), bar.heightAnchor.constraint(equalToConstant: 86), balancePill.leadingAnchor.constraint(equalTo: bar.leadingAnchor, constant: 14), balancePill.topAnchor.constraint(equalTo: bar.topAnchor, constant: 10), balancePill.heightAnchor.constraint(equalToConstant: 42), balancePill.widthAnchor.constraint(equalToConstant: 126), coin.leadingAnchor.constraint(equalTo: balancePill.leadingAnchor, constant: 14), coin.centerYAnchor.constraint(equalTo: balancePill.centerYAnchor), balance.leadingAnchor.constraint(equalTo: coin.trailingAnchor, constant: 7), balance.centerYAnchor.constraint(equalTo: balancePill.centerYAnchor), recharge.trailingAnchor.constraint(equalTo: bar.trailingAnchor, constant: -14), recharge.topAnchor.constraint(equalTo: bar.topAnchor, constant: 10), recharge.heightAnchor.constraint(equalToConstant: 42), recharge.widthAnchor.constraint(equalToConstant: 140)]) }
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int { items.count }
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell { let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "storeItem", for: indexPath) as! EffectCatalogCell; cell.configure(items[indexPath.item], owned: LookMeExperienceStore.shared.backpack.contains(where: { $0.id == items[indexPath.item].id })); return cell }
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize { CGSize(width: (collectionView.bounds.width - 42) / 3, height: 160) }
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) { let item = items[indexPath.item]; if LookMeExperienceStore.shared.buy(id: item.id, name: item.name, symbol: item.symbol, price: item.price) { CoinPrompt.spent(from: self, amount: item.price, activity: "\(item.name) was added to your Backpack") } else { CoinPrompt.insufficient(from: self, required: item.price, activity: item.name) { [weak self] in self?.navigationController?.pushViewController(CoinVaultViewController(), animated: true) } } }
    func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView { let header = collectionView.dequeueReusableSupplementaryView(ofKind: kind, withReuseIdentifier: "storeHeader", for: indexPath) as! EffectCatalogHeader; header.configure(selected: category) { [weak self] value in self?.category = value; self?.collectionView.reloadData() }; return header }
    private func refreshBalance() { balance.text = LookMeExperienceStore.shared.coins.formatted() }
    @objc private func rechargeTapped() { navigationController?.pushViewController(CoinVaultViewController(), animated: true) }
    private func toast(_ message: String) { let a = UIAlertController(title: message, message: nil, preferredStyle: .alert); present(a, animated: true); DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) { a.dismiss(animated: true) } }
}

final class EffectCatalogHeader: UICollectionReusableView {
    private let art = UIImageView(image: UIImage(named: "effect-boutique-aurora.png")); private let categories = UIStackView(); private var action: ((String) -> Void)?
    override init(frame: CGRect) { super.init(frame: frame); art.contentMode = .scaleAspectFill; art.round(0); art.translatesAutoresizingMaskIntoConstraints = false; addSubview(art); let overlay = UIView(); overlay.translatesAutoresizingMaskIntoConstraints = false; art.addSubview(overlay); DispatchQueue.main.async { LMTheme.gradient(overlay, colors: [.clear, LMTheme.background], horizontal: false) }; let label = UILabel.lm("THE GIFT VAULT", size: 11, weight: .heavy); label.letterSpacing(1.4); let title = UILabel.lm("Make their moment glow", size: 22, weight: .bold); [label,title].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; addSubview($0) }; categories.axis = .horizontal; categories.spacing = 8; categories.translatesAutoresizingMaskIntoConstraints = false; addSubview(categories); NSLayoutConstraint.activate([art.topAnchor.constraint(equalTo: topAnchor), art.leadingAnchor.constraint(equalTo: leadingAnchor, constant: -12), art.trailingAnchor.constraint(equalTo: trailingAnchor, constant: 12), art.heightAnchor.constraint(equalToConstant: 176), overlay.topAnchor.constraint(equalTo: art.topAnchor), overlay.leadingAnchor.constraint(equalTo: art.leadingAnchor), overlay.trailingAnchor.constraint(equalTo: art.trailingAnchor), overlay.bottomAnchor.constraint(equalTo: art.bottomAnchor), label.leadingAnchor.constraint(equalTo: leadingAnchor, constant: 4), label.topAnchor.constraint(equalTo: topAnchor, constant: 75), title.leadingAnchor.constraint(equalTo: label.leadingAnchor), title.topAnchor.constraint(equalTo: label.bottomAnchor, constant: 7), categories.topAnchor.constraint(equalTo: art.bottomAnchor, constant: 15), categories.leadingAnchor.constraint(equalTo: leadingAnchor), categories.trailingAnchor.constraint(lessThanOrEqualTo: trailingAnchor), categories.heightAnchor.constraint(equalToConstant: 34)]) }
    required init?(coder: NSCoder) { fatalError() }
    func configure(selected: String, action: @escaping (String) -> Void) { self.action = action; categories.arrangedSubviews.forEach { $0.removeFromSuperview() }; ["All", "Live Gift", "Entrance FX", "Profile Aura"].forEach { value in let b = UIButton(type: .system); b.setTitle(value, for: .normal); b.setTitleColor(value == selected ? .white : LMTheme.muted, for: .normal); b.titleLabel?.font = LMTheme.font(size: 11, weight: .bold); b.backgroundColor = value == selected ? LMTheme.pink.withAlphaComponent(0.88) : LMTheme.panel; b.round(16); b.widthAnchor.constraint(equalToConstant: value == "All" ? 54 : 88).isActive = true; b.addAction(UIAction { [weak self] _ in self?.action?(value) }, for: .touchUpInside); categories.addArrangedSubview(b) } }
}

final class EffectCatalogCell: UICollectionViewCell {
    private let art = UILabel.lm(size: 42); private let name = UILabel.lm(size: 11, weight: .bold); private let state = UILabel.lm(size: 9, weight: .semibold, color: LMTheme.muted); private let price = UILabel.lm(size: 10, weight: .bold, color: LMTheme.pinkSoft)
    override init(frame: CGRect) { super.init(frame: frame); contentView.backgroundColor = LMTheme.panel; contentView.round(8); contentView.layer.borderWidth = 0.5; contentView.layer.borderColor = UIColor.white.withAlphaComponent(0.07).cgColor; art.textAlignment = .center; name.textAlignment = .center; state.textAlignment = .center; state.backgroundColor = LMTheme.background.withAlphaComponent(0.65); state.round(8); price.textAlignment = .center; [art,name,state,price].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview($0) }; NSLayoutConstraint.activate([art.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 14), art.centerXAnchor.constraint(equalTo: contentView.centerXAnchor), name.topAnchor.constraint(equalTo: art.bottomAnchor, constant: 8), name.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 4), name.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -4), state.topAnchor.constraint(equalTo: name.bottomAnchor, constant: 7), state.centerXAnchor.constraint(equalTo: contentView.centerXAnchor), state.heightAnchor.constraint(equalToConstant: 17), state.widthAnchor.constraint(equalToConstant: 74), price.topAnchor.constraint(equalTo: state.bottomAnchor, constant: 7), price.centerXAnchor.constraint(equalTo: contentView.centerXAnchor)]) }
    required init?(coder: NSCoder) { fatalError() }
    func configure(_ item: EffectCatalogItem, owned: Bool) { art.text = item.symbol; name.text = item.name; state.text = owned ? "In Backpack" : "Tap to collect"; state.textColor = owned ? .systemGreen : LMTheme.muted; price.text = "● \(item.price)"; contentView.layer.borderColor = owned ? LMTheme.pink.withAlphaComponent(0.6).cgColor : UIColor.white.withAlphaComponent(0.07).cgColor; contentView.layer.borderWidth = owned ? 1 : 0.5 }
}

final class BackpackViewController: LMViewController, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    private var collectionView: UICollectionView!
    override func viewDidLoad() { super.viewDidLoad(); title = "Backpack"; let layout = UICollectionViewFlowLayout(); layout.minimumLineSpacing = 12; layout.minimumInteritemSpacing = 10; layout.sectionInset = UIEdgeInsets(top: 18, left: 14, bottom: 20, right: 14); collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout); collectionView.backgroundColor = .clear; collectionView.dataSource = self; collectionView.delegate = self; collectionView.register(CollectedEffectCell.self, forCellWithReuseIdentifier: "bag"); view.addSubview(collectionView); collectionView.pin(to: view) }
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int { max(1, LookMeExperienceStore.shared.backpack.count) }
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell { let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "bag", for: indexPath) as! CollectedEffectCell; if LookMeExperienceStore.shared.backpack.isEmpty { cell.configureEmpty() } else { cell.configure(LookMeExperienceStore.shared.backpack[indexPath.item]) }; return cell }
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize { LookMeExperienceStore.shared.backpack.isEmpty ? CGSize(width: collectionView.bounds.width - 28, height: 210) : CGSize(width: (collectionView.bounds.width - 38) / 2, height: 170) }
}

final class CollectedEffectCell: UICollectionViewCell {
    private let symbol = UILabel.lm(size: 44); private let title = UILabel.lm(size: 14, weight: .bold); private let note = UILabel.lm(size: 11, color: LMTheme.muted)
    override init(frame: CGRect) { super.init(frame: frame); contentView.backgroundColor = LMTheme.panel; contentView.round(11); [symbol,title,note].forEach { $0.textAlignment = .center; $0.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview($0) }; NSLayoutConstraint.activate([symbol.centerXAnchor.constraint(equalTo: contentView.centerXAnchor), symbol.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 30), title.topAnchor.constraint(equalTo: symbol.bottomAnchor, constant: 10), title.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 8), title.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -8), note.topAnchor.constraint(equalTo: title.bottomAnchor, constant: 6), note.leadingAnchor.constraint(equalTo: title.leadingAnchor), note.trailingAnchor.constraint(equalTo: title.trailingAnchor)]) }
    required init?(coder: NSCoder) { fatalError() }
    func configure(_ item: CollectedEffectRecord) { symbol.text = item.symbol; title.text = item.name; note.text = "Quantity  ×\(item.quantity)" }
    func configureEmpty() { symbol.text = "🎒"; title.text = "Your backpack is empty"; note.text = "Collect effects and gifts from the Store" }
}

private extension UILabel { func letterSpacing(_ value: CGFloat) { guard let text else { return }; attributedText = NSAttributedString(string: text, attributes: [.kern: value, .foregroundColor: textColor as Any, .font: font as Any]) } }
