import UIKit

final class MutualConversationViewController: LMViewController, UITableViewDataSource {
    private let member: CommunityProfile; private let table = UITableView(); private let field = UITextField(); private let composer = UIView()
    private var messages: [DirectConversationEntry] { LookMeExperienceStore.shared.messages.filter { $0.memberID == member.id } }
    init(member: CommunityProfile) { self.member = member; super.init(nibName: nil, bundle: nil) }
    required init?(coder: NSCoder) { fatalError() }
    override func viewDidLoad() {
        super.viewDidLoad(); navigationItem.leftItemsSupplementBackButton = true; navigationItem.leftBarButtonItem = avatarBarButton(); navigationItem.titleView = chatTitle(); navigationItem.rightBarButtonItems = [UIBarButtonItem(image: UIImage(systemName: "ellipsis"), style: .plain, target: self, action: #selector(safety)), UIBarButtonItem(image: UIImage(systemName: "video.fill"), style: .plain, target: self, action: #selector(videoCall)), UIBarButtonItem(image: UIImage(systemName: "phone.fill"), style: .plain, target: self, action: #selector(voiceCall))]
        table.backgroundColor = .clear; table.separatorStyle = .none; table.dataSource = self; table.keyboardDismissMode = .interactive; table.contentInset = UIEdgeInsets(top: 12, left: 0, bottom: 12, right: 0); table.register(MessageBubbleCell.self, forCellReuseIdentifier: "bubble"); view.addSubview(table)
        composer.backgroundColor = LMTheme.background; composer.layer.borderWidth = 0.5; composer.layer.borderColor = UIColor.white.withAlphaComponent(0.07).cgColor; composer.translatesAutoresizingMaskIntoConstraints = false; view.addSubview(composer)
        let add = UIButton(type: .system); add.setImage(UIImage(systemName: "plus.circle.fill", withConfiguration: UIImage.SymbolConfiguration(pointSize: 25)), for: .normal); add.tintColor = LMTheme.muted; add.translatesAutoresizingMaskIntoConstraints = false; composer.addSubview(add)
        field.attributedPlaceholder = NSAttributedString(string: "Write a message", attributes: [.foregroundColor: LMTheme.muted]); field.textColor = .white; field.font = LMTheme.font(size: 14, weight: .medium); field.backgroundColor = LMTheme.panel; field.layer.cornerRadius = 21; field.setLeftPadding(14); field.returnKeyType = .send; field.addTarget(self, action: #selector(sendMessage), for: .editingDidEndOnExit); field.translatesAutoresizingMaskIntoConstraints = false; composer.addSubview(field)
        let send = UIButton(type: .system); send.setImage(UIImage(systemName: "paperplane.fill", withConfiguration: UIImage.SymbolConfiguration(pointSize: 18, weight: .bold)), for: .normal); send.tintColor = .white; send.backgroundColor = LMTheme.pink; send.round(20); send.translatesAutoresizingMaskIntoConstraints = false; send.addTarget(self, action: #selector(sendMessage), for: .touchUpInside); composer.addSubview(send); table.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([composer.leadingAnchor.constraint(equalTo: view.leadingAnchor), composer.trailingAnchor.constraint(equalTo: view.trailingAnchor), composer.bottomAnchor.constraint(equalTo: view.keyboardLayoutGuide.topAnchor), composer.heightAnchor.constraint(equalToConstant: 66), add.leadingAnchor.constraint(equalTo: composer.leadingAnchor, constant: 11), add.centerYAnchor.constraint(equalTo: composer.centerYAnchor), add.widthAnchor.constraint(equalToConstant: 30), add.heightAnchor.constraint(equalTo: add.widthAnchor), field.leadingAnchor.constraint(equalTo: add.trailingAnchor, constant: 7), field.centerYAnchor.constraint(equalTo: composer.centerYAnchor), field.heightAnchor.constraint(equalToConstant: 43), send.leadingAnchor.constraint(equalTo: field.trailingAnchor, constant: 7), send.trailingAnchor.constraint(equalTo: composer.trailingAnchor, constant: -10), send.centerYAnchor.constraint(equalTo: composer.centerYAnchor), send.widthAnchor.constraint(equalToConstant: 40), send.heightAnchor.constraint(equalTo: send.widthAnchor), table.topAnchor.constraint(equalTo: view.topAnchor), table.leadingAnchor.constraint(equalTo: view.leadingAnchor), table.trailingAnchor.constraint(equalTo: view.trailingAnchor), table.bottomAnchor.constraint(equalTo: composer.topAnchor)])
        NotificationCenter.default.addObserver(forName: .lookMeStoreChanged, object: nil, queue: .main) { [weak self] _ in guard let self else { return }; if LookMeExperienceStore.shared.blockedUsers.contains(self.member.id) { self.navigationController?.popViewController(animated: true) } else { self.table.reloadData(); self.scrollBottom() } }; scrollBottom()
    }
    private func avatarBarButton() -> UIBarButtonItem { let button = UIButton(type: .system); button.setImage(UIImage(named: member.image)?.withRenderingMode(.alwaysOriginal), for: .normal); button.imageView?.contentMode = .scaleAspectFill; button.round(17); button.widthAnchor.constraint(equalToConstant: 34).isActive = true; button.heightAnchor.constraint(equalToConstant: 34).isActive = true; button.accessibilityLabel = "Open \(member.name)'s profile"; button.addTarget(self, action: #selector(openProfile), for: .touchUpInside); return UIBarButtonItem(customView: button) }
    private func chatTitle() -> UIView { let box = UIView(frame: CGRect(x: 0, y: 0, width: 105, height: 42)); let name = UILabel.lm(member.name, size: 14, weight: .bold); let status = UILabel.lm(member.isLive ? "● online" : "recently active", size: 10, weight: .medium, color: member.isLive ? .systemGreen : LMTheme.muted); [name,status].forEach { $0.translatesAutoresizingMaskIntoConstraints = false; box.addSubview($0) }; NSLayoutConstraint.activate([name.leadingAnchor.constraint(equalTo: box.leadingAnchor), name.topAnchor.constraint(equalTo: box.topAnchor, constant: 5), status.leadingAnchor.constraint(equalTo: name.leadingAnchor), status.topAnchor.constraint(equalTo: name.bottomAnchor, constant: 1)]); return box }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int { messages.count }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell { let cell = tableView.dequeueReusableCell(withIdentifier: "bubble", for: indexPath) as! MessageBubbleCell; cell.configure(messages[indexPath.row], avatar: member.image); return cell }
    @objc private func sendMessage() { guard let text = field.text?.trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty else { return }; guard LookMeContentPolicy.allows(text) else { present(LMNoticeViewController(style: .warning, title: "Message not sent", message: "Please revise content that may be unsafe, explicit, threatening or spam-like."), animated: true); return }; guardMutual { [weak self] in guard let self else { return }; LookMeExperienceStore.shared.send(text, to: member.id); field.text = "" } }
    @objc private func voiceCall() { guardMutual { [weak self] in guard let self else { return }; CallPermissionManager.request(video: false, from: self) { self.present(VideoCallViewController(member: self.member, mode: .voice), animated: true) } } }
    @objc private func videoCall() { guardMutual { [weak self] in guard let self else { return }; CallPermissionManager.request(video: true, from: self) { self.present(VideoCallViewController(member: self.member, mode: .video), animated: true) } } }
    @objc private func openProfile() { navigationController?.pushViewController(CommunityProfileDetailViewController(member: member), animated: true) }
    @objc private func safety() { SafetyCoordinator.present(from: self, target: .init(id: "chat:\(member.id)", type: "conversation", userID: member.id, displayName: member.name)) }
    private func guardMutual(_ action: () -> Void) { guard LookMeExperienceStore.shared.isMutual(with: member.id) else { present(LMNoticeViewController(style: .warning, title: "Mutual follow required", message: "You and \(member.name) must both choose to follow each other before messaging or calling."), animated: true); return }; action() }
    private func scrollBottom() { DispatchQueue.main.async { guard !self.messages.isEmpty else { return }; self.table.scrollToRow(at: IndexPath(row: self.messages.count - 1, section: 0), at: .bottom, animated: true) } }
}

final class MessageBubbleCell: UITableViewCell {
    private let bubble = UIView(); private let label = UILabel.lm(size: 14, weight: .medium); private let time = UILabel.lm(size: 9, color: LMTheme.muted); private let avatar = UIImageView(); private var leading: NSLayoutConstraint!; private var trailing: NSLayoutConstraint!; private var avatarLeading: NSLayoutConstraint!
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier); backgroundColor = .clear; selectionStyle = .none
        avatar.contentMode = .scaleAspectFill; avatar.round(13); avatar.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview(avatar)
        bubble.round(17); bubble.translatesAutoresizingMaskIntoConstraints = false; contentView.addSubview(bubble); label.numberOfLines = 0; label.translatesAutoresizingMaskIntoConstraints = false; time.translatesAutoresizingMaskIntoConstraints = false; bubble.addSubview(label); bubble.addSubview(time)
        leading = bubble.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 48); trailing = bubble.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: -14); avatarLeading = avatar.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 14)
        NSLayoutConstraint.activate([bubble.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 6), bubble.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -6), bubble.widthAnchor.constraint(lessThanOrEqualTo: contentView.widthAnchor, multiplier: 0.72), label.topAnchor.constraint(equalTo: bubble.topAnchor, constant: 10), label.leadingAnchor.constraint(equalTo: bubble.leadingAnchor, constant: 13), label.trailingAnchor.constraint(equalTo: bubble.trailingAnchor, constant: -13), time.topAnchor.constraint(equalTo: label.bottomAnchor, constant: 4), time.trailingAnchor.constraint(equalTo: bubble.trailingAnchor, constant: -11), time.bottomAnchor.constraint(equalTo: bubble.bottomAnchor, constant: -7), avatarLeading, avatar.bottomAnchor.constraint(equalTo: bubble.bottomAnchor), avatar.widthAnchor.constraint(equalToConstant: 26), avatar.heightAnchor.constraint(equalTo: avatar.widthAnchor)])
    }
    required init?(coder: NSCoder) { fatalError() }
    func configure(_ message: DirectConversationEntry, avatar imageName: String) { label.text = message.text; time.text = DateFormatter.chatTime.string(from: message.sentAt); bubble.backgroundColor = message.isMine ? LMTheme.pink : LMTheme.panel2; time.textColor = message.isMine ? .white.withAlphaComponent(0.67) : LMTheme.muted; leading.isActive = !message.isMine; trailing.isActive = message.isMine; avatar.isHidden = message.isMine; avatar.image = UIImage(named: imageName) }
}

private extension DateFormatter { static let chatTime: DateFormatter = { let f = DateFormatter(); f.dateFormat = "HH:mm"; return f }() }
